# Generated by Django 4.1.2 on 2024-02-03 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Todo",
        ),
    ]
